---
- hosts: localhost
  connection: local
  tasks:
    - name: Stop Instances
      ec2_instance_info:
        region: ap-southeast-1
      register: ec2_info
 
    - name: displaying output
      debug: msg="{{item.instance_id}}"
      with_items: "{{ec2_info.instances}}"
 
    - name: start
      ec2_instance:
        instance_ids: "{{item.instance_id}}"
        region: ap-southeast-1
        state: stopped
        wait: no
      with_items: "{{ec2_info.instances}}"
